debug/passwords_in_source - re-implement as OK/DONE/TODO
logic is
  bad if there are hits (anywhere in history)
  worse if they are on HEAD (changing the password will break stuff)

no colours
org-mode output
sanitise the search phrases

runs in ~6m on intcvs1 with
  time nice -20 ionice -c3 ./passwords_in_source | tee passwords_in_source.log

diff --git a/debug/passwords_in_source b/debug/passwords_in_source
--- a/debug/passwords_in_source
+++ b/debug/passwords_in_source
@@ -2,42 +2,76 @@
 
 main() {
     ptnfile="$( cd $( dirname "$0" ); pwd )/$( basename "$0" ).ptn"
+    [ -f "$ptnfile" ] || {
+        echo "$0: Need patterns file, one per line for '[git] grep -E -f $ptnfile'" >&2
+        exit 4
+    }
 
-    # Assume nothing about my working copy, look at origin/master or origin MAIN
-    searchy ~/gitwk-anacode/anacode--BROKEN  origin/cvs/main
-    searchy ~/gitwk-anacode/ensembl--BROKEN  origin/cvs/main
-    searchy ~/gitwk-anacode/ensembl-pipeline origin/cvs/main
+    sloow=$( ionice -p$$ )
+    [ "$sloow" = 'idle' ] || echo "[w] Running with ionice class '$sloow', try 'ionice -c3' ?" >&2
 
-    searchy ~/gitwk-anacode/ensembl-otter    origin/master
-    searchy ~/gitwk-anacode/team_tools       origin/master
-    searchy ~/gitwk-anacode/assembly_viewer  origin/master
-    searchy ~/gitwk-anacode/PipeMon          origin/master
+    printf -- '-*- org -*- # an emacs folding mode\n\n'
+    for repo in $( intcvs1_list_repos ); do
+        searchy "$repo"
+    done | sanitise_hits
 }
 
-decolour() {
-    perl -pe ' s{\x1b\[(\d+(;\d+)?)?[mK]}{}g '
+sanitise_hits() {
+    perl -MFile::Slurp=slurp -pE '
+ BEGIN {
+   push @ptn, slurp(shift);
+   chomp @ptn;
+   $ptn = join "|", @ptn;
+   $| = 1;
+ }
+ s/($ptn)/"*" x length($1)/eg
+ ' $ptnfile
+}
+
+
+intcvs1_list_repos() {
+    local devs
+
+    [ $( hostname -s ) = 'intcvs1' ] || {
+        echo "Run me on intcvs1.  Too complicated otherwise, to get quoting right." >&2
+        exit 5
+    }
+
+    devs=$( getent group anacode | cut -d: -f4 ) # csv with dups
+    find /repos/git/anacode /repos/git/users/{$devs} -name HEAD -type f 2>/dev/null \
+        | perl -pe 's{(\/logs)?\/HEAD}{}' | sort -u
 }
 
 searchy() {
-    local branch hits nhit
-    cd $1
-    branch=$2
+    local dir branch all_hits all_nhit tip_hits tip_nhit state
+    dir="$1"
+    cd "$dir" || exit 6
 
-    # git-grep(1) will only look at our latest commit
-    hits=$( git grep --color=always -i -E -f "$ptnfile" -a -n  $branch )
-    nhit="$( printf "%s\n" "$hits" | wc -l )"
+    branch="$( git head || echo HEAD )" # 'git head' is part of git-yacontrib
+    commit=$( git log -1 --format=%h $branch 2>&1 ) || {
+        printf '* %-4s %25s %s\n%s\n\n' 'FAIL' '' "$dir" "$commit"
+        return
+    }
 
-    if [ -z "$hits" ]; then
-        # Super-thorough but rather vague about where the hit was found
-        branch="(everything)"
-        hits=$( git fast-export --all | grep -a -i -E --color=always -C5 -n -f "$ptnfile" )
-        nhit="$( printf "%s\n" "$hits" | decolour | grep -E '^[0-9]+:' | wc -l )"
-    fi
+    # Super-thorough but rather vague about where the hit was found
+    all_hits="$( git fast-export --all | grep -a -i -E -f "$ptnfile" 2>&1 )"
+    all_nhit="$( printf '%s\n' "$all_hits" | wc -l )"
+    [ -z "$all_hits" ] && all_nhit=0
 
-    printf "\n   %s hits in %s on %s\n" $nhit "$(pwd)" "$branch"
-    if [ -n "$hits" ]; then
-        printf "%s\n" "$hits"
-    fi
+    # git-grep(1) HEAD, to tell "is the problem now fixed?"
+    tip_hits="$( git grep -i -E -f "$ptnfile" -a -n $commit 2>&1 )"
+    tip_nhit="$( printf '%s\n' "$tip_hits" | wc -l )"
+    [ -z "$tip_hits" ] && tip_nhit=0
+
+    case "$all_nhit,$tip_nhit" in
+        0,0) state=OK ;;
+        *,0) state=DONE ;;
+        *,*) state=TODO ;;
+    esac
+
+    printf '* %-4s %25s %s\n' $state "(all:$all_nhit $branch:$tip_nhit)" "$dir"
+    [ -n "$tip_hits" ] && printf '** Hits in %s (%s)\n%s\n' $commit $branch "$tip_hits"
+    [ -n "$all_hits" ] && printf '** All hits (no location info)\n%s\n\n' "$all_hits"
 }
 
 main
