otterlace_build: abort the client install immediately if the ZMap build directory is missing.

diff --git a/otterlace/release/scripts/otterlace_build b/otterlace/release/scripts/otterlace_build
--- a/otterlace/release/scripts/otterlace_build
+++ b/otterlace/release/scripts/otterlace_build
@@ -215,14 +215,6 @@ otterlace_client_install_scripts() {
 }
 
 otterlace_client_install_zmap() {
-
-    # sanity test
-    if ! [ -d "$zmap_prefix" ]
-    then
-        echo "error: client ZMap install for ${arch} aborted: the ZMap directory '${zmap_prefix} is missing or invalid" >&2
-        exit 1
-    fi
-
     local install_dir bin_dir build_dir
     install_dir="$1"
     bin_dir="${install_dir}/bin"
@@ -268,6 +260,13 @@ otterlace_client_install() {
     echo "host name: $( hostname )"
     echo "arch: ${arch}"
     echo "debian version: $( cat /etc/debian_version )"
+
+    # sanity test
+    if ! [ -d "$zmap_prefix" ]
+    then
+        echo "error: client install for ${arch} aborted: the ZMap directory '${zmap_prefix} is missing or invalid" >&2
+        exit 1
+    fi
 
     otterlace_local="/software/anacode/bin/otterlace_rel${version}"
 
