git-hooks for managing new server-config repo
doc in bin/server-config-op

diff --git a/git-hooks/server-config/update b/git-hooks/server-config/update
--- a/git-hooks/server-config/update
+++ b/git-hooks/server-config/update
@@ -10,15 +10,6 @@
 # hooks.allowunannotated
 #   This boolean sets whether unannotated tags will be allowed into the
 #   repository.  By default they won't be.
-# hooks.allowdeletetag
-#   This boolean sets whether deleting tags will be allowed in the
-#   repository.  By default they won't be.
-# hooks.allowmodifytag
-#   This boolean sets whether a tag may be modified after creation. By default
-#   it won't be.
-# hooks.allowdeletebranch
-#   This boolean sets whether deleting branches will be allowed in the
-#   repository.  By default they won't be.
 # hooks.denycreatebranch
 #   This boolean sets whether remotely creating branches will be denied
 #   in the repository.  By default this is allowed.
@@ -44,10 +35,7 @@ fi
 
 # --- Config
 allowunannotated=$(git config --bool hooks.allowunannotated)
-allowdeletebranch=$(git config --bool hooks.allowdeletebranch)
 denycreatebranch=$(git config --bool hooks.denycreatebranch)
-allowdeletetag=$(git config --bool hooks.allowdeletetag)
-allowmodifytag=$(git config --bool hooks.allowmodifytag)
 
 # check for no description
 projectdesc=$(sed -e '1q' "$GIT_DIR/description")
@@ -68,54 +56,49 @@ else
 fi
 
 case "$refname","$newrev_type" in
-	refs/tags/*,commit)
-		# un-annotated tag
-		short_refname=${refname##refs/tags/}
-		if [ "$allowunannotated" != "true" ]; then
-			echo "*** The un-annotated tag, $short_refname, is not allowed in this repository" >&2
-			echo "*** Use 'git tag [ -a | -s ]' for tags you want to propagate." >&2
-			exit 1
-		fi
-		;;
 	refs/tags/*,delete)
 		# delete tag
-		if [ "$allowdeletetag" != "true" ]; then
-			echo "*** Deleting a tag is not allowed in this repository" >&2
-			exit 1
-		fi
+		# (allow it as a get-out)
 		;;
-	refs/tags/*,tag)
+	refs/tags/*,tag|refs/tags/*,commit)
 		# annotated tag
-		if [ "$allowmodifytag" != "true" ] && git rev-parse $refname > /dev/null 2>&1
+		# un-annotated tag
+		if git rev-parse $refname > /dev/null 2>&1
 		then
 			echo "*** Tag '$refname' already exists." >&2
-			echo "*** Modifying a tag is not allowed in this repository." >&2
+			echo "*** Modifying a tag is not allowed in this repository (and is anyway often ineffective)." >&2
 			exit 1
 		fi
 		;;
 	refs/heads/*,commit)
 		# branch
 		if [ "$oldrev" = "$zero" -a "$denycreatebranch" = "true" ]; then
-			echo "*** Creating a branch is not allowed in this repository" >&2
-			exit 1
+                    # create
+		    echo "*** Creating a branch is not allowed in this repository" >&2
+		    exit 1
+                elif [ "$refname" = "refs/heads/live" ]; then
+                    # push to 'live' branch
+		    if git rev-parse dev > /dev/null 2>&1 && git log --format=%H dev | grep -x -q "$newrev"; then
+                        # seen on dev = OK
+                        :
+                    else
+                        echo "*** Cannot accept push $refname=$newrev until it has been pushed to dev." >&2
+                        exit 1
+                    fi
 		fi
 		;;
 	refs/heads/*,delete)
 		# delete branch
-		if [ "$allowdeletebranch" != "true" ]; then
-			echo "*** Deleting a branch is not allowed in this repository" >&2
-			exit 1
-		fi
+		echo "*** Explicitly deleting a branch is not allowed in this repository.  Please push a commit containing no files, so it can be merged." >&2
+		exit 1
 		;;
 	refs/remotes/*,commit)
 		# tracking branch
+		echo "*** No remote branches allowed here ($GIT_DIR)" >&2
+                exit 1
 		;;
 	refs/remotes/*,delete)
 		# delete tracking branch
-		if [ "$allowdeletebranch" != "true" ]; then
-			echo "*** Deleting a tracking branch is not allowed in this repository" >&2
-			exit 1
-		fi
 		;;
 	*)
 		# Anything else (is there anything else?)
